### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pajoda** [pajoda/recavel#8]
## Recavel Roadmap

- [ ] Write tests for the functions that currently exist soon before it takes years to write all tests afterwards
- [ ] Link exceptions to responses if recording is enabled (and don't record twice then)
- [ ] Implement the config (don't record requests and responses if disabled for example)
- [ ] Don't record requests, responses and exceptions directly (use queue
- [ ] Show records of requests, responses and exceptions in a beautiful dashboard
- [ ] Corporate Design (includes colors, logo & more)

Order is random, the dashboard clearly depends on the corporate design for example.

_(more like a ToDo, but roadmap looks way cooler)™_
